---
names:
- Producent Baterii Rigel S.A.
- Акционерное Общество "Аккумуляторная Компания "Ригель""
- Дружество за акумулаторни батерии „Ригел“ АД
- Spoločnosť na výrobu batérií Rigeľ a. s.
- Societatea de baterii Rigel SA
- Rigel
- Joint Stock Company "Battery Company "Rigel""
- Battery Company Rigel JSC
- Société par actions Battery Company Rigel
source: eu-data
entity_type: organization
country: ''
birthdate: ''
ref_number: EU.9731.44
ref_type: EU Reference Number
remark: 
