---
names:
- Producent Baterii Rigel S.A.
- Société par actions Battery Company Rigel
- Rigel
- Joint Stock Company "Battery Company "Rigel""
- Battery Company Rigel JSC
- Societatea de baterii Rigel SA
- Дружество за акумулаторни батерии „Ригел“ АД
- Акционерное Общество "Аккумуляторная Компания "Ригель""
- Spoločnosť na výrobu batérií Rigeľ a. s.
source: eu-data
entity_type: organization
country: ''
birthdate: ''
ref_number: EU.9731.44
ref_type: EU Reference Number
remark:
